fix(ci-build): streamline frontend build steps and adjust working directory for Nuxt output

diff --git a/.github/workflows/ci-build.yaml b/.github/workflows/ci-build.yaml
--- a/.github/workflows/ci-build.yaml
+++ b/.github/workflows/ci-build.yaml
@@ -77,9 +77,7 @@ jobs:
     if: needs.gate.outputs.proceed == 'true'
     name: Frontend Build
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./app
+
     steps:
       - uses: actions/checkout@v4
 
@@ -100,21 +98,31 @@ jobs:
 
       - name: Enable pnpm
         run: corepack enable
+        working-directory: ./app
 
       - name: Install dependencies
         run: pnpm install
 
       - name: Lint
         run: pnpm run lint --fix
+        working-directory: ./app
 
       - name: Build Nuxt
         run: pnpm run build
+        working-directory: ./app
+
+      - name: Debug Nuxt output
+        run: |
+          pwd
+          ls -R
+          echo "------ app/.output ------"
+          ls -R app/.output || echo "app/.output NOT FOUND"
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
         with:
           name: nuxt-output
-          path: app/.output/**
+          path: app/.output/
 
   build-and-push:
     environment: development
